apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  containers:
    - name: jenkins
      image: jenkins/jenkins:lts
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: "name"
                operator: NotIn
                values:
                  - workernde1
                  - workernode2
